# Aufgaben zur Datenonvertierung - Aufgabe 1
print("========================")
print("Umwandlung von int zu float")
print("")
x = int(10)
print(x,type(x))
print("Umwandung zu float ergibt folgendes Ergebnis:    ")
y = float(x)
print(y,type (y))
print("========================")
# Aufgaben zur Datenonvertierung - Aufgabe 1
print("========================")
print("Umwandlung von float zu int")
print("")
x = float(17.23781)
print(x,type(x))
print("Umwandung zu int ergibt folgendes Ergebnis:    ")
y = int(x)
print(y,type (y))
print("========================")
# Aufgaben zur Datenonvertierung - Aufgabe 4
print("========================")
print("Umwandlung von float zu int & float")
print("")
x = float(17.23781)
print(x,type(x))
print("Umwandung zu int & float ergibt folgendes Ergebnis:    ")
y = int(x)
print(y,type (y))
z = float(x)
print(z, type(z))
print("========================")


