print("")
print("         --- Kleiner Preisrechner ---            ")
print("")
benutzer_eingabe1 = input("Geben Sie den Gewünschten Artikel an       ")        
Artikel = str(benutzer_eingabe1)
benutzer_eingabe2 = input("Geben Sie den Preis an                     ")
Preis = float(benutzer_eingabe2)
benutzer_eingabe3 = input("Geben Sie die Anzahl an                    ")
Anzahl = int(benutzer_eingabe3)
Mwst = float(0.19)
Mwst_Gesamt = round(Preis*Anzahl*Mwst,2)
Gesamtnettopreis = round(Preis*Anzahl,2)
Gesamtbruttopreis = round(Preis*Anzahl*Mwst+Preis*Anzahl,2)
print("")
print("")
print("        --- Bestellzusammenfassung ---         ")
print("")
print(f"Produkt:            {Artikel}")
print(f"Gesamtnettopreis:   {Gesamtnettopreis:.2f} €")
print(f"+19% Mwst:          {Mwst_Gesamt:.2f} €")
print(f"Gesamtbruttopreis:  {Gesamtbruttopreis:.2f} €")
print("")
print("        --- Bestellzusammenfassung ---         ")
print("")