a = float(22.50)
b = float(12.00)
c = float(36.00)
__name__ = str("Max Mustermann")
Tageslohn = round(a*b,2)
Wochenlohn = round(a*c,2)
print("")
print(__name__)

print(f"Der aktuelle Stundenlohn von {__name__} beträgt:               {a:.2f}€ Brutto")
print(f"Die aktuelle Arbeitszeit von {__name__} je Tag beträgt:        {b} Stunden")
print(f"Die aktuelle Wochenarbeitszeit von {__name__} beträgt:         {c} Stunden")
print(f"Es ergibt sich ein Tageslohn von:                                  {Tageslohn:.2f}€ Brutto")
print(f"Es ergibt sich ein Wochenlohn von:                                 {Wochenlohn:.2f}€ Brutto")
